---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

# set AD datas ==================================================================================================
- name: "play servers AD configuration"
  hosts: server
  roles:
    - { role: 'member_server', tags: 'server'}
  vars:
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{admin_user}}@{{member_domain}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"

- name: "play workstations AD configuration"
  hosts: workstation
  roles:
    - { role: 'commonwkstn', tags: 'workstation'}
    - { role: 'settings/hostname', tags: 'hostname' }
  vars:
    member_domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{admin_user}}@{{member_domain}}"
    domain_password: "{{lab.domains[member_domain].domain_password}}"
    hostname: "{{lab.hosts[dict_key].hostname}}"

- name: "play linux servers AD configuration"
  hosts: linux_domain
  become: true
  become_method: sudo
  roles:
    - { role: 'linux/add_linux_to_domain', tags: 'linux_domain'}
  vars:
    sudoers_group: "{{lab.hosts[dict_key].local_groups.sudoers | default([])}}"
    ssh_group: "{{lab.hosts[dict_key].local_groups.ssh | default([])}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    dc_key: "{{lab.domains[domain].dc}}"
    dc_name: "{{lab.hosts[dc_key].hostname}}"
    dc_fqdn: "{{dc_name}}.{{domain}}"
    hostname: "{{lab.hosts[dict_key].hostname}}"
    dc_ip: "{{hostvars[dc_key].ansible_host}}"
    domain_username: "{{admin_user}}"
    domain_password: "{{lab.domains[domain].domain_password}}"

- name: Setup DNS records for linux machines on all domain controllers
  hosts: dc
  tasks:
    - name: Add DNS record for each linux_domain machine
      include_role:
        name: add_dns_record
      vars:
        domain: "{{ lab.hosts[item].domain }}"
        record_name: "{{ lab.hosts[item].hostname }}"
        record_type: "A"
        record_value: "{{ hostvars[item].ansible_host }}"
      loop: "{{ groups['linux_domain'] }}"
      loop_control:
        loop_var: item
